### ISSUE TITLE
Add guides to documentation

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/axon#162]
Here is an (incomplete) list of guides that should be added to the documentation:

- [x] Basic Axon models
- [x] Complex Models (combinators, weight sharing, etc.)
- [ ] Working with Named Tensors (requires #57)
- [ ] Training and Evaluating Axon models
- [x] Creating Custom Layers
- [ ] Custom Training Loops
- [ ] Creating Custom Event Handlers and Metrics
- [ ] Mixed Precision Training
- [ ] Axon Graph Manipulation (requires #117)
- [ ] Pruning trained models (requires #120)
- [ ] Model Serialization and Saving (requires #26)
- [x] Hooks (requires #77)
- [ ] Axon Optimization Deep Dive
- [ ] Transfer Learning and Fine Tuning

Note these differ from examples of specific applications of Axon as they are intended to be example based deep dives of certain aspects of the API.

**Comment by josevalim** [comment]
Just a note: Livebook supports links in more recent versions, so you can have a root guide that points to all other guides. :)
